petclinic_user = "petclinic" # Username for the petclinic application
petclinic_mysql_pwd = "my-password" # Password for the petclinic application
cidr_vpc = "10.0.0.0/16" # CIDR Block for AWS VPC
availability_zones = ["eu-west-3a", "eu-west-3b"] # AWS Availability zones
cidr_public_subnets = ["10.0.0.0/24", "10.0.1.0/24"] # CIDR Blocks for public subnets
cidr_private_subnets = ["10.0.2.0/24", "10.0.3.0/24"] # CIDR Blocks for private subnets
aws_account_id = "aws-account-id"
cluster_name = "petclinic"
secret_key = "my-secret-key"
access_key = "my-access-key"
sns_topic_arn = "my-sns-topic-arn"
email= "it.abdenour.djouder@gmail.com"
